default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: stimulus_todomvc_development

test:
  <<: *default
  database: stimulus_todomvc_test

production:
  <<: *default
  database: stimulus_todomvc_production
  username: stimulus_todomvc
  password: <%= ENV['STIMULUS_TODOMVC_DATABASE_PASSWORD'] %>
